version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8085:8085"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://dpg-d0k6ort6ubrc73b13av0-a.singapore-postgres.render.com:5432/auth_db_ujy7
    networks:
      - cloth-shop-network

volumes:
  db_data:

networks:
  cloth-shop-network:
    external: true
